# Generated by Django 4.2.30 on 2026-06-27 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReqSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Неизвестно', max_length=200, verbose_name='Название')),
                ('author', models.CharField(default='Неизвестно', max_length=200, verbose_name='Автор')),
                ('album', models.CharField(default='Неизвестно', max_length=200, verbose_name='Альбом')),
                ('duration', models.IntegerField(default=0, verbose_name='Длительность сек')),
                ('cover', models.ImageField(default='browser/img/logo.jpg', upload_to='', verbose_name='Обложка альбома')),
                ('requester', models.CharField(default='Неизвестный', max_length=200, verbose_name='Заказал')),
            ],
            options={
                'verbose_name': 'Заказанная песня',
                'verbose_name_plural': 'Заказанные песни',
            },
        ),
        migrations.CreateModel(
            name='SongPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('songs', models.ManyToManyField(blank=True, related_name='choosed', to='songqueue.reqsongs')),
                ('users', models.ManyToManyField(blank=True, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
