# Generated by Django 6.0.5 on 2026-06-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReqSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название')),
                ('author', models.CharField(verbose_name='Автор')),
                ('album', models.CharField(verbose_name='Альбом')),
                ('duration', models.DurationField(verbose_name='Длительность')),
            ],
        ),
    ]
