# Generated by Django 6.0.5 on 2026-06-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songqueue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reqsongs',
            options={'verbose_name': 'Заказанная песня', 'verbose_name_plural': 'Заказанные песни'},
        ),
        migrations.AddField(
            model_name='reqsongs',
            name='cover',
            field=models.ImageField(default='browser/img/logo.jpg', upload_to='', verbose_name='Обложка альбома'),
        ),
    ]
