# Generated by Django 6.0.5 on 2026-06-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songqueue', '0002_alter_reqsongs_options_reqsongs_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqsongs',
            name='duration',
            field=models.IntegerField(verbose_name='Длительность'),
        ),
    ]
