# Generated by Django 4.2.30 on 2026-06-28 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songqueue', '0002_remove_songpoll_users_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='songpoll',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='songqueue.reqsongs'),
        ),
    ]
