# Generated by Django 6.0.5 on 2026-06-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songqueue', '0003_alter_reqsongs_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqsongs',
            name='cover_color',
            field=models.CharField(default='(41, 41, 41)', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='reqsongs',
            name='duration',
            field=models.DurationField(verbose_name='Длительность'),
        ),
    ]
