# Generated by Django 4.2.30 on 2026-06-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songqueue', '0003_songpoll_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqsongs',
            name='trackid',
            field=models.IntegerField(default=0, verbose_name='Айди трека'),
        ),
    ]
