# Generated by Django 6.0.5 on 2026-06-05 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songqueue', '0004_reqsongs_cover_color_alter_reqsongs_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reqsongs',
            name='cover_color',
        ),
    ]
