# Generated by Django 6.0.5 on 2026-06-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songqueue', '0005_remove_reqsongs_cover_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqsongs',
            name='duration',
            field=models.IntegerField(verbose_name='Длительность сек'),
        ),
    ]
