# Generated by Django 6.0.5 on 2026-06-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songqueue', '0006_alter_reqsongs_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqsongs',
            name='requester',
            field=models.CharField(default='Неизвестный', verbose_name='Заказал'),
        ),
    ]
