# Generated by Django 6.0.5 on 2026-06-22 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songqueue', '0007_reqsongs_requester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SongPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songs', models.ManyToManyField(blank=True, related_name='choosed', to='songqueue.reqsongs')),
                ('users', models.ManyToManyField(blank=True, related_name='choosed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
