# Generated by Django 6.0.5 on 2026-06-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_userprofile_avatar_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='browser/img/default-avatar.png', upload_to='avatars/'),
        ),
    ]
