# Generated by Django 6.0.5 on 2026-06-11 17:27

import uuid

from django.db import migrations

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("dashboard", "UserProfile")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_userprofile_uuid'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
