# Generated by Django 6.0.5 on 2026-06-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20260611_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='default-avatar.png', upload_to='avatars/'),
        ),
    ]
