# Generated by Django 6.0.5 on 2026-06-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_userprofile_avatar_alter_userprofile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatars/default-avatar.webp', upload_to='avatars/'),
        ),
    ]
